### ISSUE TITLE
Minified version doesn't work

### ISSUE THREAD

**Issue by aminsol** [tracker1/cryptico-js#10]
Minified version doesn't work but if I take the unminified version and minify it myself it does work!

**Comment by cjavad** [comment]
Works fine here, are you using the browser version? if you're what doesn't work?

**Comment by tracker1** [comment]
I've gotta review some things with it, I don't think the build env was working correctly for me recently, so need to do some tweaks.

**Comment by pwFoo** [comment]
Hi, is the problem solved? Searching for a solution to sign, verify, encrypt and decrypt messages.

**Comment by aminsol** [comment]
It was a year ago but If I remember correctly I was doing something wrong. Go ahead and use it.

**Comment by pwFoo** [comment]
Hi @aminsol,
thanks for answering here.
Do you also know if signing / verify without encrypt is possible? #13

**Comment by tracker1** [comment]
@aminsol thanks for the update, sorry I totally lost on even looking into this one... haven't touched it in a very long time... I'd actually suggest moving to web crypto api if you can over this library.
