### ISSUE TITLE
Encryption using private key

### ISSUE THREAD

**Issue by developeranirudhprabhu** [tracker1/cryptico-js#12]
All the example demonstrated here are using public key for encryption and private key for decryption. Is there means by which we can encrypt using private key and decrypt using public key?

**Comment by tracker1** [comment]
should be able to swap the key you are using to en/decrypt ... though anyone with the public key will be able to decrypt the message... usual practice in the case of authentication from sender is to sign the message with the private key that can then be verified with the public.

note: I didn't write the original library and haven't touched it in quite a while.

**Comment by developeranirudhprabhu** [comment]
It's not about sign and verification. It's about sharing some data.

**Comment by tracker1** [comment]
@developeranirudhprabhu gotcha, as I said, you should just be able to swap the private/public keys on the encrypt/decrypt methods.
