### ISSUE TITLE
Sign without encrypt?

### ISSUE THREAD

**Issue by pwFoo** [tracker1/cryptico-js#13]
Is it possible to just sign a message without encrypt it?
Just for sender verification at recipients side?

**Comment by aminsol** [comment]
If you just want to verify something just use checksum or something like that. 
If you want to do integrity check then no. You have to encrypt the message

**Comment by pwFoo** [comment]
I read about Cryptico that the key could be insecure because of identical generated public keys(?)

For security reasons I would encrypt, but just sign would be nice to verify the sender I think?

**Comment by aminsol** [comment]
Yes, that's right. Here is how public and private key works regardless of what library you use:
PrivateKey --sign--> Message ---> Only Public key can open the message: ensures the integrity of the message
PublicKey -----sign--> Message -----> Only Private key can open the message: ensures the  confidentiality

**Comment by pwFoo** [comment]
So signing would work in both directions, ok. I planned singing with private key to verify with public. To be sure private key owner is the sender.

So "key owner" as sender is verified (and optional encrypted by recipient public key). Key owner as recipient should be encrypted (optional signed with sender pub key).
So if it would not possible to encrypt (why ever...) The message should be signed to be sure about sender identity.

But it looks like only sign with private key isn't implemented in much libraries. 

Sign with public key doesn't help to identify sender, so it have to be sender's private key for signing.
"Verify" recipient isn't needed because that is done by encrypt with recipients public key and to decrypt private key is needed.

**Comment by aminsol** [comment]
> So "key owner" as sender is verified (and optional encrypted by recipient public key). Key owner as recipient should be encrypted (~optional signed with sender pub key~).

(`optional signed with owner pub key`)

Yes, it's like this:
sender-->encrypt w/sender private-->encrypt w/receiver public(optional)-- |`internet`| ---> decrypt w/receiver private(optional)--> decrypt w/sender public-->receiver

**Comment by pwFoo** [comment]
Sign  with pub key? 
Shouldn't singing be done with private key to be sure about the person? Public key is known to all, so (sender) public key signing doesn't help the recipient I think? That way it simple should be encrypted with recipient public key (and optional signed with sender private key).

So recipient decrypt with private key and verify signature with senders public key.

It's a little bit confusing writing about... but I think we mean the same thing? *g*


At the moment I take a look into https://github.com/stanwar/simplecrypto, which looks good and encrypt / decrypt really fast with the crypto api.

**Comment by aminsol** [comment]
Yes sign with the public key and only the person who has the private key can open that message.

**Comment by tracker1** [comment]
The bottom of the readme mentions a signing extension[1] you can try... I didn't do much to the original library, just packaged for easier node use a long time ago.  You can also, as mentioned, encrypt with the private key, and anyone with the public key can decrypt (effectively signing).. depending on your needs.

Also, if you are supporting modern browsers, you can give a look at web crypto api[2][3], which does provide quite a bit.  Node has a lot of this type of support in the box now too.

[1] https://img.atwikiimg.com/www9.atwiki.jp/kurushima/pub/jsrsa/
[2] https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API
[3] https://caniuse.com/#feat=cryptography
