### ISSUE TITLE
Allow signing without encrypting.

### ISSUE THREAD

**Issue by boadadf** [tracker1/cryptico-js#9]
Hi there. For a project of my own I am using your library. Thanks for sharing it with all of us.

The thing is that I need to send signed messages without encrypting them. With a small change in the api.js you could allow signing and verifying messages without having to encrypt them. It is all about decoupling the signing and verifying code blocks from inside the encrypt and decrypt methods respectively and creating separated methods for them.

I tried creating a branch and a merge request to push it but I can't. If you are interested you can do the change by yourself or adding me as contributor so I can push it for your review:

`my.encrypt = function(plaintext, publickeystring, signingkey)
    {
        var cipherblock = "";
        var aeskey = my.generateAESKey();
        try
        {
            var publickey = my.publicKeyFromString(publickeystring);
            cipherblock += my.b16to64(publickey.encrypt(my.bytes2string(aeskey))) + "?";
        }
        catch(err)
        {
            return {status: "Invalid public key"};
        }
        if(signingkey)
        {
            plaintext += my.sign(plaintext, signingkey);		
        }
        cipherblock += my.encryptAESCBC(plaintext, aeskey);    
        return {status: "success", cipher: cipherblock};
    }
    my.decrypt = function(ciphertext, key)
    {
        var cipherblock = ciphertext.split("?");
        var aeskey = key.decrypt(my.b64to16(cipherblock[0]));
        if(aeskey == null)
        {
            return {status: "failure"};
        }
        aeskey = my.string2bytes(aeskey);
        var plaintext = my.decryptAESCBC(cipherblock[1], aeskey);
        if(plaintext.indexOf("::52cee64bb3a38f6403386519a39ac91c::")!=-1)
        {
            return my.verify(plaintext);
        }
        else
        {
            return {status: "success", plaintext: plaintext[0], signature: "unsigned"};
        }
    }

    my.sign = function(plaintext, signingkey)
    {
        var signString = cryptico.b16to64(signingkey.signString(plaintext, "sha256"));
        plaintext += "::52cee64bb3a38f6403386519a39ac91c::";
        plaintext += cryptico.publicKeyString(signingkey);
        plaintext += "::52cee64bb3a38f6403386519a39ac91c::";
        plaintext += signString;
        return plaintext;
    }

    my.verify = function(plaintext)
    {
    	plaintext = plaintext.split("::52cee64bb3a38f6403386519a39ac91c::");
        if(plaintext.length == 3)
        {
            var publickey = my.publicKeyFromString(plaintext[1]);
            var signature = my.b64to16(plaintext[2]);
            if(publickey.verifyString(plaintext[0], signature))
            {
                return {status: "success", 
                        plaintext: plaintext[0], 
                        signature: "verified", 
                        publicKeyString: my.publicKeyString(publickey)};
            }
            else
            {
                return {status: "success", 
                        plaintext: plaintext[0], 
                        signature: "forged", 
                        publicKeyString: my.publicKeyString(publickey)};
            }
        }
        else
        {
            return {status: "failure"};
        }
    }`

**Comment by tracker1** [comment]
If you submit a PR, happy to get it in... :-)

**Comment by tracker1** [comment]
Added, will publish after I can test a few pieces...
